[workspace]
members = [
    "challenge",
    "loyalty",
    "coupon",
    "signature",
    "shop",
]
exclude = [
    "challenge/meta",
    "challenge/wasm",
    "loyalty/meta",
    "loyalty/wasm",
    "coupon/meta",
    "coupon/wasm",
    "signature/meta",
    "signature/wasm",
    "shop/meta",
    "shop/wasm",
]
resolver = "2"
